"""add image_urls column to ticket

Revision ID: 115cd2c18a84
Revises: 3c3a6f5f3e55
Create Date: 2026-02-09 16:00:52.364301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115cd2c18a84'
down_revision: Union[str, Sequence[str], None] = '3c3a6f5f3e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_chunk'), 'knowledge_embeddings', type_='foreignkey')
    op.add_column('ticket', sa.Column('image_urls', sa.JSON(), nullable=True))
    op.drop_column('ticket', 'issue_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('issue_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('ticket', 'image_urls')
    op.create_foreign_key(op.f('fk_chunk'), 'knowledge_embeddings', 'knowledge_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
