"""add issue_type to ticket

Revision ID: 3c3a6f5f3e55
Revises: 0015_add_ticket_table
Create Date: 2026-02-09 11:05:54.471250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c3a6f5f3e55'
down_revision = '0015_add_ticket_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('knowledge_article_versions', 'content_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('knowledge_article_versions', 'created_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint(op.f('knowledge_article_versions_article_id_version_key'), 'knowledge_article_versions', type_='unique')
    op.create_unique_constraint('uq_article_version', 'knowledge_article_versions', ['article_id', 'version'])
    op.drop_constraint(op.f('knowledge_article_versions_article_id_fkey'), 'knowledge_article_versions', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_article_versions', 'knowledge_articles', ['article_id'], ['id'])
    op.drop_index(op.f('idx_knowledge_articles_upload_session_id'), table_name='knowledge_articles')
    op.drop_constraint(op.f('knowledge_articles_upload_session_id_fkey'), 'knowledge_articles', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_articles', 'knowledge_uploads', ['upload_session_id'], ['id'])
    op.alter_column('knowledge_chunk_tags', 'tag',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_index(op.f('idx_knowledge_chunk_tags_tag'), table_name='knowledge_chunk_tags')
    op.drop_index(op.f('ix_knowledge_chunk_tags_tag'), table_name='knowledge_chunk_tags')
    op.drop_constraint(op.f('knowledge_chunk_tags_chunk_id_fkey'), 'knowledge_chunk_tags', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_chunk_tags', 'knowledge_chunks', ['chunk_id'], ['id'])
    op.alter_column('knowledge_chunks', 'chunk_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_index(op.f('idx_knowledge_chunks_article_version'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_hash'), table_name='knowledge_chunks')
    op.drop_constraint(op.f('knowledge_chunks_article_id_version_chunk_index_key'), 'knowledge_chunks', type_='unique')
    op.create_unique_constraint('uq_chunk_index', 'knowledge_chunks', ['article_id', 'version', 'chunk_index'])
    op.drop_constraint(op.f('knowledge_chunks_article_id_fkey'), 'knowledge_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_chunks', 'knowledge_articles', ['article_id'], ['id'])
    op.alter_column('knowledge_embeddings', 'model',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_knowledge_embeddings_article_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('idx_knowledge_embeddings_chunk_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_chunk_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('knowledge_embeddings_embedding_idx'), table_name='knowledge_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('knowledge_embeddings_hnsw'), table_name='knowledge_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(op.f('knowledge_embeddings_chunk_id_fkey'), 'knowledge_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge_embeddings', 'knowledge_chunks', ['chunk_id'], ['id'])
    op.alter_column('knowledge_uploads', 'uploaded_by',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_message_conversation_id'), table_name='message')
    op.drop_index(op.f('ix_product_attribute_values_attribute_id_value'), table_name='product_attribute_values')
    op.drop_index(op.f('ux_product_attribute_values_product_id_attribute_id'), table_name='product_attribute_values')
    op.alter_column('product_embeddings', 'source_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_product_embeddings_source_hash'), table_name='product_embeddings')
    op.drop_index(op.f('ux_product_embeddings_product_model'), table_name='product_embeddings')
    op.create_index(op.f('ix_product_embeddings_source_hash'), 'product_embeddings', ['source_hash'], unique=False)
    op.drop_constraint(op.f('product_embeddings_product_id_fkey'), 'product_embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'product_embeddings', 'products', ['product_id'], ['id'])
    op.alter_column('product_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('product_groups_master_code_key'), 'product_groups', type_='unique')
    op.create_index(op.f('ix_product_groups_master_code'), 'product_groups', ['master_code'], unique=True)
    op.alter_column('product_uploads', 'rows_processed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('product_uploads', 'progress_percentage',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_products_search_hash'), table_name='products')
    op.create_index(op.f('ix_products_group_id'), 'products', ['group_id'], unique=False)
    op.drop_index(op.f('ix_semantic_cache_lookup'), table_name='semantic_cache')
    op.create_index(op.f('ix_semantic_cache_expires_at'), 'semantic_cache', ['expires_at'], unique=False)
    op.add_column('ticket', sa.Column('issue_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket', 'issue_type')
    op.drop_index(op.f('ix_semantic_cache_expires_at'), table_name='semantic_cache')
    op.create_index(op.f('ix_semantic_cache_lookup'), 'semantic_cache', ['reply_language', 'target_currency', 'expires_at'], unique=False)
    op.drop_index(op.f('ix_products_group_id'), table_name='products')
    op.create_index(op.f('idx_products_search_hash'), 'products', ['search_hash'], unique=False)
    op.alter_column('product_uploads', 'progress_percentage',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('product_uploads', 'rows_processed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_product_groups_master_code'), table_name='product_groups')
    op.create_unique_constraint(op.f('product_groups_master_code_key'), 'product_groups', ['master_code'], postgresql_nulls_not_distinct=False)
    op.alter_column('product_groups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(None, 'product_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('product_embeddings_product_id_fkey'), 'product_embeddings', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_product_embeddings_source_hash'), table_name='product_embeddings')
    op.create_index(op.f('ux_product_embeddings_product_model'), 'product_embeddings', ['product_id', 'model'], unique=True)
    op.create_index(op.f('idx_product_embeddings_source_hash'), 'product_embeddings', ['source_hash'], unique=False)
    op.alter_column('product_embeddings', 'source_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('ux_product_attribute_values_product_id_attribute_id'), 'product_attribute_values', ['product_id', 'attribute_id'], unique=True)
    op.create_index(op.f('ix_product_attribute_values_attribute_id_value'), 'product_attribute_values', ['attribute_id', 'value'], unique=False)
    op.create_index(op.f('idx_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.alter_column('knowledge_uploads', 'uploaded_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'knowledge_embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_embeddings_chunk_id_fkey'), 'knowledge_embeddings', 'knowledge_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('knowledge_embeddings_hnsw'), 'knowledge_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('knowledge_embeddings_embedding_idx'), 'knowledge_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('ix_knowledge_embeddings_chunk_id'), 'knowledge_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('idx_knowledge_embeddings_chunk_id'), 'knowledge_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('idx_knowledge_embeddings_article_id'), 'knowledge_embeddings', ['article_id'], unique=False)
    op.alter_column('knowledge_embeddings', 'model',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'knowledge_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_chunks_article_id_fkey'), 'knowledge_chunks', 'knowledge_articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_chunk_index', 'knowledge_chunks', type_='unique')
    op.create_unique_constraint(op.f('knowledge_chunks_article_id_version_chunk_index_key'), 'knowledge_chunks', ['article_id', 'version', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_knowledge_chunks_hash'), 'knowledge_chunks', ['chunk_hash'], unique=False)
    op.create_index(op.f('idx_knowledge_chunks_article_version'), 'knowledge_chunks', ['article_id', 'version'], unique=False)
    op.alter_column('knowledge_chunks', 'chunk_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint(None, 'knowledge_chunk_tags', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_chunk_tags_chunk_id_fkey'), 'knowledge_chunk_tags', 'knowledge_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_knowledge_chunk_tags_tag'), 'knowledge_chunk_tags', ['tag'], unique=False)
    op.create_index(op.f('idx_knowledge_chunk_tags_tag'), 'knowledge_chunk_tags', ['tag'], unique=False)
    op.alter_column('knowledge_chunk_tags', 'tag',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_constraint(None, 'knowledge_articles', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_articles_upload_session_id_fkey'), 'knowledge_articles', 'knowledge_uploads', ['upload_session_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_knowledge_articles_upload_session_id'), 'knowledge_articles', ['upload_session_id'], unique=False)
    op.drop_constraint(None, 'knowledge_article_versions', type_='foreignkey')
    op.create_foreign_key(op.f('knowledge_article_versions_article_id_fkey'), 'knowledge_article_versions', 'knowledge_articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_article_version', 'knowledge_article_versions', type_='unique')
    op.create_unique_constraint(op.f('knowledge_article_versions_article_id_version_key'), 'knowledge_article_versions', ['article_id', 'version'], postgresql_nulls_not_distinct=False)
    op.alter_column('knowledge_article_versions', 'created_by',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('knowledge_article_versions', 'content_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
